language: go

before_script:
  - go get -u github.com/mattn/goveralls

script: # to allow coverage pass, change repo name to github.com/mellanox
  - make
  - make test-coverage
  - goveralls -coverprofile=ib-kubernetes.cover -service=travis-ci
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
     bash -c '
     docker push $IMAGE_NAME;
     echo done'
    on:
      branch: master
